# Generated by Django 2.1.1 on 2018-09-07 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_auto_20180907_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='published_on',
            new_name='published_date',
        ),
    ]
